### PR TITLE
saved data visible

### PR DESCRIPTION
**Pull request by RilAbbSnehaM**

### CODE REVIEW

**Comment by Jiggy9** [comment]
Keep my updated project and then againsend PR, as there's conflict in profile_page file

**Comment by RilAbbSnehaM** [comment]
> Keep my updated project and then againsend PR, as there's conflict in profile_page file

ok

**Comment by RilAbbSnehaM** [comment]
again conflict occur

**Comment by Jiggy9** [comment]
> again conflict occur

Check discord

**Pull request closed without merging**
