### PR TITLE
Fix Black Screen on Back Navigation from Profile Page

### LINKED ISSUE #59: [BUG] : Returning back from profile page leads to black screen
# Bug : 
- when you click the **back arrow** button in the profile appBar it leads to black screen.
-  small issue can be resolved easily.

WhatsApp Image 2024-10-13 at 01 15 38

### PR DESCRIPTION
**Pull request by may-tas**
# Resolves #59 
- Removed back button as it was creating issues everywhere from home page , feedback, settings and profile page.
- Also fixed navigation from account page so that when user clicks back button, he is redirected to settings page with the bottom_navigation intact.

## some more issues : 
- I think the bottom navigation bar is very inefficient and creates a lot of issue, also the navigation is all over the place so I think using GoRouter would be efficient.
- I will open a new issue for this and resolve the navigation.

### CODE REVIEW

**Comment by Jiggy9** [comment]
@may-tas could you elaborate that how nav bar causing issues?

**Comment by may-tas** [comment]
> @may-tas could you elaborate that how nav bar causing issues?

- Yes, first thing is that the code for bottom navigation is too clustered and big which is not at all necessary.
- When you are navigating to any screen for e.g navigating to account page from settings tab, then the bottom navigation bar is gone and not visible.
-  When you navigate to profile screen from account page then also the navigation bar is not there.
-  Navigation Bar should always be sticked to the bottom screen except for some screens which are not there in bottom tab , for e.g for accounts page it is fine if the navigation bar is not there but when you navigate to profile screen from account page, the navigation bar should be present as it is a part of the tabs of navigation bar.

**Comment by Jiggy9** [comment]
I see, I suggest you to work on navbar but make it efficient, put it where it's necessary and remove from where it's not necessary like that.. but don't remove it, as it's easier to move screen for users.. as it makes app user friendly.. also u can make nav bar stylish if you've in your mind

> > @may-tas could you elaborate that how nav bar causing issues?
> 
> * Yes, first thing is that the code for bottom navigation is too clustered and big which is not at all necessary.
> * When you are navigating to any screen for e.g navigating to account page from settings tab, then the bottom navigation bar is gone and not visible.
> * When you navigate to profile screen from account page then also the navigation bar is not there.
> * Navigation Bar should always be sticked to the bottom screen except for some screens which are not there in bottom tab , for e.g for accounts page it is fine if the navigation bar is not there but when you navigate to profile screen from account page, the navigation bar should be present as it is a part of the tabs of navigation bar.

**Comment by may-tas** [comment]
Yes @Jiggy9 I can work on it.

**Comment by may-tas** [comment]
Should I open an issue for it or Just start the work and make a PR.

**Comment by may-tas** [comment]
I'll make it look better and more modern than before.

**Comment by Jiggy9** [comment]
> Should I open an issue for it or Just start the work and make a PR.

Open issue I'll assign, then you can start work

**Comment by may-tas** [comment]
> > Should I open an issue for it or Just start the work and make a PR.
> 
> Open issue I'll assign, then you can start work

okay

**Pull request merged**
