### PR TITLE
Profile section save button not working after putting data #16

### PR DESCRIPTION
**Pull request by nisarg107**
Upgraded firebase dependencies and changed minsdkversion from 21 to 23. Also handled, if image is selected properly then only saved to storage

### CODE REVIEW

**Comment by Jiggy9** [comment]
> Upgraded firebase dependencies and changed minsdkversion from 21 to 23. Also handled, if image is selected properly then only saved to storage

If issue already exists then mention issue here

**Comment by nisarg107** [comment]
no issue you can merge this but connect with firebase cli

**Comment by Jiggy9** [comment]
> no issue you can merge this but connect with firebase cli

I mean check repository issues, if the solution is related to it then mention it here, if not then open issue first then send pull request with mention.. After than I'll merge it

**Comment by nisarg107** [comment]
Profile section save button not working after putting data #16

Solution: In this i have upgraded firebase dependencies , changed minsdkversion and handled savechanges function in profilepage.dart

**Comment by Jiggy9** [comment]
> Profile section save button not working after putting data #16
> 
> Solution: In this i have upgraded firebase dependencies , changed minsdkversion and handled savechanges function in profilepage.dart

Also reply in issue comment

**Comment by Jiggy9** [comment]
#16 completed

**Pull request merged**
