### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by neeru24**
I have updated the readme.md. Kindly merge it. Thank you :)
@Jiggy9  @EfrataAron Check it 

Screenshot 2024-10-06 124117

image

### CODE REVIEW

**Comment by EfrataAron** [comment]
the ReadMe file looks good to go. I like how it has been reorganized.

**Comment by neeru24** [comment]
> the ReadMe file looks good to go. I like how it has been reorganized.

Kindly merge it

**Comment by Jiggy9** [comment]
@neeru24 Thanks you for your contribution.

**Comment by neeru24** [comment]
> @neeru24 Thanks you for your contribution.

Thanks for the opportunity
Can you pls add the level too...:)

**Comment by Jiggy9** [comment]
> Thanks for the opportunity Can you pls add the level too...:)

Hey documentation issues no need levels labels! Hope to see your further contribution in other issues!

**Pull request merged**
