### PR TITLE
CONTRIBUTING.md

### LINKED ISSUE #2: Missing CONTRIBUTING.md file
**Description:**

The `CONTRIBUTING.md` file is missing from the JCT repository. This file is essential for guiding new contributors through the process of setting up the project, adhering to coding standards, and submitting pull requests. Without it, contributors may lack clarity on how to effectively contribute to the project, which could lead to inconsistencies and confusion.

I recommend adding a `CONTRIBUTING.md` file to outline:
- Steps for setting up the repository locally.
- Branching and submission of pull requests.
- Code style guidelines and best practices.
- How to report issues and propose new features.

Please @Jiggy9 assign me this task with labels "GSSOC-Ext", "Hacktoberfest-accepted" and"level1".

### PR DESCRIPTION
**Pull request by archanasingh11**
Missing Contributing.md file
## Description
This pull request enhances the CONTRIBUTING.md file for the JCT by providing clearer guidelines and a more structured format. 

## Related Issues

- Closes #2 

## Type of PR

- [X] (Documentation update)

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/andoriyaprashant)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by archanasingh11** [comment]
Hey @Jiggy9 I have raised the PR
Thanks

**Comment by archanasingh11** [comment]
Hey @Jiggy9 please assign me the labels "gssoc-ext-24" , "hacktoberfest-accepted" 
i request you to assign me this label

**Comment by Jiggy9** [comment]
> Hey @Jiggy9 please assign me the labels "gssoc-ext-24" , "hacktoberfest-accepted" i request you to assign me this label

Already assigned labels as guidelines. Don't worry I'll modify if it needs to. Thank you for contributing!

**Comment by archanasingh11** [comment]
> > Hey @Jiggy9 please assign me the labels "gssoc-ext-24" , "hacktoberfest-accepted" i request you to assign me this label
> 
> Already assigned labels as guidelines. Don't worry I'll modify if it needs to. Thank you for contributing!

Do modife it @Jiggy9 as its not showing up  actually u entered this labels with wrong spelling.

**Comment by Jiggy9** [comment]
> > > Hey @Jiggy9 please assign me the labels "gssoc-ext-24" , "hacktoberfest-accepted" i request you to assign me this label
> > 
> > 
> > Already assigned labels as guidelines. Don't worry I'll modify if it needs to. Thank you for contributing!
> 
> Do modife it @Jiggy9 as its not showing up actually u entered this labels with wrong spelling.

Screenshot_20241005_112739_Chrome
This is correct label and it's already added.

**Comment by archanasingh11** [comment]
Please @Jiggy9  add label "level1" or else my contribution is not counted

**Pull request merged**
